"""Initial migration: create users and messages tables

Revision ID: 7464da01617a
Revises:
Create Date: 2025-05-14 13:39:37.461594

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7464da01617a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pseudonym", sa.String(length=80), nullable=False),
        sa.Column("connected_at", sa.DateTime(), nullable=True),
        sa.Column("is_connected", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pseudonym"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("users")
    # ### end Alembic commands ###
